### ISSUE TITLE
failed reading of star file

### ISSUE THREAD

**Issue by alisterburt** [brisvag/blik#121]
for the following file (truncated here)
```

# version 30001

data_optics

loop_ 
_rlnOpticsGroup #1 
_rlnOpticsGroupName #2 
_rlnSphericalAberration #3 
_rlnVoltage #4 
_rlnImagePixelSize #5 
_rlnImageSize #6 
_rlnImageDimensionality #7 
           1 opticsGroup1     1.733000   300.000000     3.300000          168            3 
           2 opticsGroup2     1.342000   300.000000     3.300000          168            3 
           3 opticsGroup3     4.727000   300.000000     3.300000          168            3 
           4 opticsGroup4     -0.71100   300.000000     3.300000          168            3 
           5 opticsGroup5     -0.20100   300.000000     3.300000          168            3 
           6 opticsGroup6     1.365000   300.000000     3.300000          168            3 
           7 opticsGroup7     1.940000   300.000000     3.300000          168            3 
           8 opticsGroup8     0.797000   300.000000     3.300000          168            3 
           9 opticsGroup9     2.208000   300.000000     3.300000          168            3 
          10 opticsGroup10     4.387000   300.000000     3.300000          168            3 
          11 opticsGroup11     1.373000   300.000000     3.300000          168            3 
          12 opticsGroup12     2.334000   300.000000     3.300000          168            3 
          13 opticsGroup13     2.712000   300.000000     3.300000          168            3 
          14 opticsGroup14     4.272000   300.000000     3.300000          168            3 
          15 opticsGroup15     3.564000   300.000000     3.300000          168            3 
          16 opticsGroup16     0.956000   300.000000     3.300000          168            3 
          17 opticsGroup17     -1.03200   300.000000     3.300000          168            3 
          18 opticsGroup18     4.942000   300.000000     3.300000          168            3 
          19 opticsGroup19     3.800000   300.000000     3.300000          168            3 
          20 opticsGroup20     1.674000   300.000000     3.300000          168            3 
          21 opticsGroup21     -1.39300   300.000000     3.300000          168            3 
          22 opticsGroup22     -0.61800   300.000000     3.300000          168            3 
          23 opticsGroup23     2.443000   300.000000     3.300000          168            3 
          24 opticsGroup24     1.801000   300.000000     3.300000          168            3 
          25 opticsGroup25     1.328000   300.000000     3.300000          168            3 
          26 opticsGroup26     1.145000   300.000000     3.300000          168            3 
          27 opticsGroup27     4.383000   300.000000     3.300000          168            3 
          28 opticsGroup28     6.647000   300.000000     3.300000          168            3 
          29 opticsGroup29     4.669000   300.000000     3.300000          168            3 
          30 opticsGroup30     1.476000   300.000000     3.300000          168            3 
          31 opticsGroup31     1.486000   300.000000     3.300000          168            3 
          32 opticsGroup32     1.284000   300.000000     3.300000          168            3 
          33 opticsGroup33     2.313000   300.000000     3.300000          168            3 
          34 opticsGroup34    12.665000   300.000000     3.300000          168            3 
          35 opticsGroup35     -5.61400   300.000000     3.300000          168            3 
          36 opticsGroup36    10.807000   300.000000     3.300000          168            3 
          37 opticsGroup37    12.419000   300.000000     3.300000          168            3 
          38 opticsGroup38    16.443000   300.000000     3.300000          168            3 
          39 opticsGroup39     -6.85400   300.000000     3.300000          168            3 
          40 opticsGroup40     2.700000   300.000000     3.300000          168            3 
          41 opticsGroup41     -2.67000   300.000000     3.300000          168            3 
          42 opticsGroup42    12.496000   300.000000     3.300000          168            3 
          43 opticsGroup43    -10.44100   300.000000     3.300000          168            3 
          44 opticsGroup44     -5.80600   300.000000     3.300000          168            3 
          45 opticsGroup45     5.766000   300.000000     3.300000          168            3 
          46 opticsGroup46    10.354000   300.000000     3.300000          168            3 
          47 opticsGroup47    21.054000   300.000000     3.300000          168            3 
          48 opticsGroup48     -2.27400   300.000000     3.300000          168            3 
          49 opticsGroup49     -5.74600   300.000000     3.300000          168            3 
          50 opticsGroup50     0.405000   300.000000     3.300000          168            3 
          51 opticsGroup51     2.600000   300.000000     3.300000          168            3 
          52 opticsGroup52     9.185000   300.000000     3.300000          168            3 
          53 opticsGroup53     -5.82000   300.000000     3.300000          168            3 
          54 opticsGroup54     -8.68600   300.000000     3.300000          168            3 
          55 opticsGroup55     8.268000   300.000000     3.300000          168            3 
          56 opticsGroup56     -3.18700   300.000000     3.300000          168            3 
          57 opticsGroup57     -2.43500   300.000000     3.300000          168            3 
          58 opticsGroup58     -6.36900   300.000000     3.300000          168            3 
          59 opticsGroup59     -5.69500   300.000000     3.300000          168            3 
          60 opticsGroup60     -4.77600   300.000000     3.300000          168            3 
          61 opticsGroup61     -1.88900   300.000000     3.300000          168            3 
          62 opticsGroup62    -19.60700   300.000000     3.300000          168            3 
          63 opticsGroup63     -6.17500   300.000000     3.300000          168            3 
          64 opticsGroup64     -5.70800   300.000000     3.300000          168            3 
          65 opticsGroup65     -4.86600   300.000000     3.300000          168            3 
          66 opticsGroup66     -3.33300   300.000000     3.300000          168            3 
          67 opticsGroup67     -3.39600   300.000000     3.300000          168            3 
          68 opticsGroup68     -6.18900   300.000000     3.300000          168            3 
          69 opticsGroup69     -6.47900   300.000000     3.300000          168            3 
          70 opticsGroup70     2.955000   300.000000     3.300000          168            3 
          71 opticsGroup71     -8.08200   300.000000     3.300000          168            3 
          72 opticsGroup72     3.985000   300.000000     3.300000          168            3 
          73 opticsGroup73     -6.77400   300.000000     3.300000          168            3 
          74 opticsGroup74    -10.19300   300.000000     3.300000          168            3 
          75 opticsGroup75     -2.01700   300.000000     3.300000          168            3 
          76 opticsGroup76    -11.01700   300.000000     3.300000          168            3 
          77 opticsGroup77     -1.76700   300.000000     3.300000          168            3 
          78 opticsGroup78     -7.98600   300.000000     3.300000          168            3 
          79 opticsGroup79    11.184000   300.000000     3.300000          168            3 
          80 opticsGroup80     -7.52300   300.000000     3.300000          168            3 
          81 opticsGroup81     -3.18100   300.000000     3.300000          168            3 
          82 opticsGroup82     0.817000   300.000000     3.300000          168            3 
          83 opticsGroup83     9.663000   300.000000     3.300000          168            3 
          84 opticsGroup84     -9.84800   300.000000     3.300000          168            3 
          85 opticsGroup85     -6.80100   300.000000     3.300000          168            3 
          86 opticsGroup86     -7.98400   300.000000     3.300000          168            3 
          87 opticsGroup87     -6.08600   300.000000     3.300000          168            3 
          88 opticsGroup88     -4.23700   300.000000     3.300000          168            3 
          89 opticsGroup89     -2.04400   300.000000     3.300000          168            3 
          90 opticsGroup90     -9.28300   300.000000     3.300000          168            3 
          91 opticsGroup91    -13.48900   300.000000     3.300000          168            3 
          92 opticsGroup92    -10.81400   300.000000     3.300000          168            3 
          93 opticsGroup93    12.717000   300.000000     3.300000          168            3 
          94 opticsGroup94     -1.35000   300.000000     3.300000          168            3 
          95 opticsGroup95     -7.84600   300.000000     3.300000          168            3 
          96 opticsGroup96     -7.04200   300.000000     3.300000          168            3 
          97 opticsGroup97    -13.21100   300.000000     3.300000          168            3 
          98 opticsGroup98    18.928000   300.000000     3.300000          168            3 
          99 opticsGroup99     -8.41000   300.000000     3.300000          168            3 
         100 opticsGroup100     -0.28500   300.000000     3.300000          168            3 
         101 opticsGroup101     -0.96000   300.000000     3.300000          168            3 
         102 opticsGroup102     -6.09200   300.000000     3.300000          168            3 
         103 opticsGroup103     -4.89400   300.000000     3.300000          168            3 
         104 opticsGroup104     7.983000   300.000000     3.300000          168            3 
         105 opticsGroup105    -11.26500   300.000000     3.300000          168            3 
         106 opticsGroup106     -5.41400   300.000000     3.300000          168            3 
         107 opticsGroup107     -4.53200   300.000000     3.300000          168            3 
         108 opticsGroup108     2.998000   300.000000     3.300000          168            3 
         109 opticsGroup109     -5.64400   300.000000     3.300000          168            3 
         110 opticsGroup110     -3.21300   300.000000     3.300000          168            3 
         111 opticsGroup111     5.510000   300.000000     3.300000          168            3 
         112 opticsGroup112     -7.84200   300.000000     3.300000          168            3 
         113 opticsGroup113     -9.12300   300.000000     3.300000          168            3 
         114 opticsGroup114     -6.93300   300.000000     3.300000          168            3 
         115 opticsGroup115     -0.18500   300.000000     3.300000          168            3 
         116 opticsGroup116    -10.37800   300.000000     3.300000          168            3 
         117 opticsGroup117     -8.54200   300.000000     3.300000          168            3 
         118 opticsGroup118     -3.12200   300.000000     3.300000          168            3 
         119 opticsGroup119     -2.92600   300.000000     3.300000          168            3 
         120 opticsGroup120     8.847000   300.000000     3.300000          168            3 
         121 opticsGroup121     -9.95900   300.000000     3.300000          168            3 
         122 opticsGroup122     -5.43400   300.000000     3.300000          168            3 
         123 opticsGroup123    10.950000   300.000000     3.300000          168            3 
         124 opticsGroup124    15.787000   300.000000     3.300000          168            3 
         125 opticsGroup125     -2.95300   300.000000     3.300000          168            3 
         126 opticsGroup126     -7.44100   300.000000     3.300000          168            3 
         127 opticsGroup127     1.529000   300.000000     3.300000          168            3 
         128 opticsGroup128     -0.75400   300.000000     3.300000          168            3 
         129 opticsGroup129     1.353000   300.000000     3.300000          168            3 
         130 opticsGroup130     -0.99700   300.000000     3.300000          168            3 
         131 opticsGroup131     0.168000   300.000000     3.300000          168            3 
         132 opticsGroup132     0.539000   300.000000     3.300000          168            3 
         133 opticsGroup133     8.163000   300.000000     3.300000          168            3 
         134 opticsGroup134     -1.10700   300.000000     3.300000          168            3 
         135 opticsGroup135     -0.74500   300.000000     3.300000          168            3 
         136 opticsGroup136     -4.76600   300.000000     3.300000          168            3 
         137 opticsGroup137    -16.87100   300.000000     3.300000          168            3 
         138 opticsGroup138     -2.16600   300.000000     3.300000          168            3 
         139 opticsGroup139     -8.19300   300.000000     3.300000          168            3 
         140 opticsGroup140    15.278000   300.000000     3.300000          168            3 
         141 opticsGroup141    13.201000   300.000000     3.300000          168            3 
         142 opticsGroup142     -3.75200   300.000000     3.300000          168            3 
         143 opticsGroup143     -3.96700   300.000000     3.300000          168            3 
         144 opticsGroup144     2.234000   300.000000     3.300000          168            3 
         145 opticsGroup145     1.923000   300.000000     3.300000          168            3 
         146 opticsGroup146     2.425000   300.000000     3.300000          168            3 
         147 opticsGroup147     1.567000   300.000000     3.300000          168            3 
         148 opticsGroup148     2.173000   300.000000     3.300000          168            3 
         149 opticsGroup149     2.639000   300.000000     3.300000          168            3 
         150 opticsGroup150     2.536000   300.000000     3.300000          168            3 
         151 opticsGroup151     1.949000   300.000000     3.300000          168            3 
         152 opticsGroup152     2.129000   300.000000     3.300000          168            3 
         153 opticsGroup153     3.710000   300.000000     3.300000          168            3 
         154 opticsGroup154     3.353000   300.000000     3.300000          168            3 
         155 opticsGroup155     3.274000   300.000000     3.300000          168            3 
         156 opticsGroup156     2.448000   300.000000     3.300000          168            3 
         157 opticsGroup157     1.160000   300.000000     3.300000          168            3 
         158 opticsGroup158     2.337000   300.000000     3.300000          168            3 
         159 opticsGroup159     2.067000   300.000000     3.300000          168            3 
         160 opticsGroup160     3.200000   300.000000     3.300000          168            3 
         161 opticsGroup161     1.977000   300.000000     3.300000          168            3 
         162 opticsGroup162     3.002000   300.000000     3.300000          168            3 
         163 opticsGroup163     2.435000   300.000000     3.300000          168            3 
         164 opticsGroup164     3.486000   300.000000     3.300000          168            3 
         165 opticsGroup165     2.795000   300.000000     3.300000          168            3 
         166 opticsGroup166     2.396000   300.000000     3.300000          168            3 
         167 opticsGroup167     1.070000   300.000000     3.300000          168            3 
         168 opticsGroup168     2.761000   300.000000     3.300000          168            3 
         169 opticsGroup169     3.698000   300.000000     3.300000          168            3 
         170 opticsGroup170     3.211000   300.000000     3.300000          168            3 
         171 opticsGroup171     3.210000   300.000000     3.300000          168            3 
         172 opticsGroup172     2.857000   300.000000     3.300000          168            3 
         173 opticsGroup173     2.462000   300.000000     3.300000          168            3 
         174 opticsGroup174     1.340000   300.000000     3.300000          168            3 
         175 opticsGroup175     3.417000   300.000000     3.300000          168            3 
         176 opticsGroup176     3.826000   300.000000     3.300000          168            3 
         177 opticsGroup177     1.357000   300.000000     3.300000          168            3 
         178 opticsGroup178     3.101000   300.000000     3.300000          168            3 
         179 opticsGroup179     3.288000   300.000000     3.300000          168            3 
         180 opticsGroup180     2.048000   300.000000     3.300000          168            3 
         181 opticsGroup181     3.676000   300.000000     3.300000          168            3 
         182 opticsGroup182     3.153000   300.000000     3.300000          168            3 
         183 opticsGroup183     0.370000   300.000000     3.300000          168            3 
         184 opticsGroup184     5.088000   300.000000     3.300000          168            3 
         185 opticsGroup185     0.895000   300.000000     3.300000          168            3 
         186 opticsGroup186     2.610000   300.000000     3.300000          168            3 
         187 opticsGroup187     3.714000   300.000000     3.300000          168            3 
         188 opticsGroup188     2.331000   300.000000     3.300000          168            3 
         189 opticsGroup189     3.156000   300.000000     3.300000          168            3 
         190 opticsGroup190     2.799000   300.000000     3.300000          168            3 
         191 opticsGroup191     2.433000   300.000000     3.300000          168            3 
         192 opticsGroup192     2.350000   300.000000     3.300000          168            3 
         193 opticsGroup193     3.083000   300.000000     3.300000          168            3 
         194 opticsGroup194     2.703000   300.000000     3.300000          168            3 
         195 opticsGroup195     5.394000   300.000000     3.300000          168            3 
         196 opticsGroup196     2.343000   300.000000     3.300000          168            3 
         197 opticsGroup197     2.168000   300.000000     3.300000          168            3 
         198 opticsGroup198     3.367000   300.000000     3.300000          168            3 
         199 opticsGroup199     2.311000   300.000000     3.300000          168            3 
         200 opticsGroup200     1.341000   300.000000     3.300000          168            3 
         201 opticsGroup201     2.756000   300.000000     3.300000          168            3 
         202 opticsGroup202     4.371000   300.000000     3.300000          168            3 
         203 opticsGroup203     4.294000   300.000000     3.300000          168            3 
         204 opticsGroup204     3.125000   300.000000     3.300000          168            3 
         205 opticsGroup205     3.881000   300.000000     3.300000          168            3 
         206 opticsGroup206     4.179000   300.000000     3.300000          168            3 
         207 opticsGroup207     2.676000   300.000000     3.300000          168            3 
         208 opticsGroup208     4.577000   300.000000     3.300000          168            3 
         209 opticsGroup209     2.384000   300.000000     3.300000          168            3 
         210 opticsGroup210     1.509000   300.000000     3.300000          168            3 
         211 opticsGroup211     2.582000   300.000000     3.300000          168            3 
         212 opticsGroup212     2.307000   300.000000     3.300000          168            3 
 

# version 30001

data_particles

loop_ 
_rlnCoordinateX #1 
_rlnCoordinateY #2 
_rlnCoordinateZ #3 
_rlnAngleRot #4 
_rlnAngleTilt #5 
_rlnAnglePsi #6 
_rlnImageName #7 
_rlnCtfImage #8 
_rlnRandomSubset #9 
_rlnPixelSize #10 
_rlnMicrographName #11 
_rlnOpticsGroup #12 
_rlnGroupNumber #13 
_rlnOriginXAngst #14 
_rlnOriginYAngst #15 
_rlnOriginZAngst #16 
_rlnClassNumber #17 
_rlnNormCorrection #18 
_rlnLogLikeliContribution #19 
_rlnMaxValueProbDistribution #20 
_rlnNrOfSignificantSamples #21 
  836.294700   862.086200   900.246400   142.071592   103.564906    69.139249 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000000_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000000_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     -1.94698     0.759021     0.165021            1     1.000000 1.859544e+07     0.347848            1 
  804.912400   965.178500   670.322700    -65.15434    74.051902    24.788571 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000001_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000001_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     0.165021     1.353021     -1.02298            1     1.000000 1.858428e+07     0.317947            6 
  752.829500   868.314300   739.809900    57.524627   101.513572    29.101890 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000002_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000002_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     0.165021     -0.42898     1.947021            1     1.000000 1.858530e+07     0.769978            5 
  879.070100   895.073900  1102.871000   131.889120   106.369129    45.962248 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000003_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000003_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     0.165021     -0.42898     -1.02298            1     1.000000 1.858327e+07     0.417911           12 
  891.395000   987.073400   743.099200   177.201641    96.547760    64.345483 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000004_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000004_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     -0.42898     0.165021     1.947021            1     1.000000 1.858951e+07     0.438819            2 
 1103.266000  1079.348000   578.694000    -45.82911    74.412707    38.652809 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000005_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000005_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     -0.42898     2.277021     -1.02298            1     1.000000 1.860413e+07     0.105477            6 
 1025.856000  1020.370000   753.358300   -128.27792    78.319160    56.221480 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000006_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000006_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     -0.42898     0.165021     0.759021            1     1.000000 1.859226e+07     0.406918            2 
  845.024800   882.678100   993.333100    68.964732   105.006347    42.480576 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000007_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000007_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     0.759021     1.353021     -0.42898            1     1.000000 1.858975e+07     0.494501            7 
 1210.012000  1134.229000   782.332500   -167.32558    82.490846    84.452430 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000008_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000008_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     0.165021     1.683021     0.165021            1     1.000000 1.857891e+07     0.472795            3 
 1092.010000  1069.259000  1025.639000   -160.29667    87.290816    76.462462 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000009_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000009_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     -1.02298     0.165021     0.165021            1     1.000000 1.859281e+07     0.154063           15 
 1194.654000  1127.082000  1070.406000    40.283766    98.223473    41.720168 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000010_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000010_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     -0.42898     1.353021     0.759021            1     1.000000 1.858563e+07     0.508501           10 
 1240.532000  1062.131000   587.446700    32.531176    89.258724    38.183493 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000011_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000011_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     0.759021     0.759021     0.165021            1     1.000000 1.857254e+07     0.286359            2 
 1066.733000  1028.368000   868.432300    20.236184    97.652883    26.430236 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000012_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000012_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     0.759021     1.353021     0.165021            1     1.000000 1.857658e+07     0.433513            1 
  828.343900   809.924200  1089.123000     9.857874    92.119779    11.866594 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000013_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000013_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     -0.42898     -0.42898     0.165021            1     1.000000 1.859472e+07     0.656570            2 
  935.039100   923.952800  1030.524000     2.826499    96.611524    34.813151 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000014_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000014_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     0.759021     -0.42898     -1.02298            1     1.000000 1.858572e+07     0.379623            3 
 1010.528000  1001.212000  1009.573000   172.983482    94.150286    71.155722 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000015_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000015_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     -1.02298     -0.42898     -1.02298            1     1.000000 1.859664e+07     0.682908            1 
 1267.484000  1167.001000   718.755600    32.894060    95.832586    71.700566 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000016_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000016_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     0.165021     1.353021     1.947021            1     1.000000 1.858123e+07     0.259793            8 
 1076.106000  1083.085000   694.161800   134.687941   101.439659    65.171771 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000017_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000017_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     0.165021     0.759021     -2.21098            1     1.000000 1.859661e+07     0.270216            9 
  971.170000   959.461900  1117.676000    86.385962   109.483393    43.903872 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000018_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000018_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     -1.35298     -1.94698     -1.02298            1     1.000000 1.860108e+07     0.204165            2 
 1219.039000  1151.760000   978.116700   109.569066   104.417065    66.857291 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000019_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000019_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     -0.42898     0.165021     0.759021            1     1.000000 1.860157e+07     0.323060            6 
 1301.657000  1146.548000   812.080400     -3.67781    87.495162    98.776776 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000020_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000020_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     0.165021     0.165021     -2.21098            1     1.000000 1.859517e+07     0.612479            8 
  951.537900   962.291100   631.813100    10.212995    98.414262    12.102395 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000021_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000021_ctf_3.30A.mrc            1     3.300000 TS.mrc.tomostar          194            1     2.277021     -0.42898     -1.02298            1     1.000000 1.858420e+07     0.268300            6 
 1035.807000  1045.579000  1096.881000   -133.55361    78.306521    70.529614 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000022_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000022_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     -0.42898     -0.42898     0.759021            1     1.000000 1.860067e+07     0.241227            2 
 1176.110000  1137.728000   880.803600   -147.27627    81.008040    77.127323 subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000023_3.30A.mrc subtomo_05Feb21/TS.mrc/TS.mrc_YTURC_0000023_ctf_3.30A.mrc            2     3.300000 TS.mrc.tomostar          194            1     -1.02298     1.353021     0.165021            1     1.000000 1.857888e+07     0.247428            8 
 1189.390000  1360.073000   476.312900   -139.76938   107.130491   118.119352 subtomo_05Feb21/TS10.mrc/TS10.mrc_YTURC_0000000_3.30A.mrc subtomo_05Feb21/TS10.mrc/TS10.mrc_YTURC_0000000_ctf_3.30A.mrc            2     3.300000 TS10.mrc.tomostar          186            2     1.947021     7.359021     -1.02298            1     1.000000 1.858866e+07     0.161733           12 
 1050.070000  1096.027000   567.046900    14.956454    92.564289     5.319966 subtomo_05Feb21/TS10.mrc/TS10.mrc_YTURC_0000001_3.30A.mrc subtomo_05Feb21/TS10.mrc/TS10.mrc_YTURC_0000001_ctf_3.30A.mrc            2     3.300000 TS10.mrc.tomostar          186            2
```

I get the following error in blik
```sh
(py) ➜  gamma-turc-subboxing blik particle_star_file.star -p 3.3
Traceback (most recent call last):
  File "/Users/aburt/mambaforge/envs/py/bin/blik", line 8, in <module>
    sys.exit(cli())
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/blik/__main__.py", line 62, in cli
    dataset = blik.read(*paths,  # noqa: F841
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/blik/utils/generic.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/blik/io_/reading/main.py", line 182, in read
    dataset = read_files(*globs, **kwargs)
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/blik/io_/reading/main.py", line 125, in read_files
    datablocks.extend(read_file(file, name_regex=name_regex, pixel_size=pixel_size,
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/blik/io_/reading/main.py", line 46, in read_file
    datablocks = listify(func(file_path, **kwargs))
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/blik/io_/reading/star.py", line 126, in read_star
    particle_blocks = reader_function(raw_data, star_path=star_path, **kwargs)
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/blik/io_/reading/star.py", line 105, in parse_relion31
    return extract_data(df, mode='RELION 3.1', **kwargs)
  File "/Users/aburt/mambaforge/envs/py/lib/python3.9/site-packages/blik/io_/reading/star.py", line 48, in extract_data
    shifts = shifts / px_size
TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''```

will look into it :)

**Comment by brisvag** [comment]
Lost track of this :p just tested on the new branch, and it's still failing. Turns out, the last 2 lines of that starfile are missing some columns with result in nans getting in the way. Might not be the same issue as back then, but at least now removing those 2 lines, everything works.
